package com.project.foodtracker.ui.product_edit


sealed class ProductDetailEditEvent {
    class OnClickSaveProductDetail(): ProductDetailEditEvent()
    class OnClickCancelProductDetail(): ProductDetailEditEvent()
    class OnClickGoBack(): ProductDetailEditEvent()
    data class OnProductTitleChanged(val title: String) : ProductDetailEditEvent()
    data class OnProductImageChanged(val image: String) : ProductDetailEditEvent()
    data class OnProductImageTypeChanged(val imageType: String) : ProductDetailEditEvent()
    data class OnProductServingsChanged(val servings: Int) : ProductDetailEditEvent()
    data class OnProductReadyInMinutesChanged(val readyInMinutes: Int) : ProductDetailEditEvent()
    data class OnProductLicenseChanged(val license: String?) : ProductDetailEditEvent()
    data class OnProductSourceNameChanged(val sourceName: String) : ProductDetailEditEvent()
    data class OnProductSourceUrlChanged(val sourceUrl: String) : ProductDetailEditEvent()
    data class OnProductSpoonacularSourceUrlChanged(val spoonacularSourceUrl: String) : ProductDetailEditEvent()
    data class OnProductHealthScoreChanged(val healthScore: Float) : ProductDetailEditEvent()
    data class OnProductSpoonacularScoreChanged(val spoonacularScore: Float) : ProductDetailEditEvent()
    data class OnProductPricePerServingChanged(val pricePerServing: Float) : ProductDetailEditEvent()
    data class OnProductCheapChanged(val cheap: Boolean) : ProductDetailEditEvent()
    data class OnProductCreditsTextChanged(val creditsText: String) : ProductDetailEditEvent()
    data class OnProductDairyFreeChanged(val dairyFree: Boolean) : ProductDetailEditEvent()
    data class OnProductGapsChanged(val gaps: String) : ProductDetailEditEvent()
    data class OnProductGlutenFreeChanged(val glutenFree: Boolean) : ProductDetailEditEvent()
    data class OnProductInstructionsChanged(val instructions: String) : ProductDetailEditEvent()
    data class OnProductKetogenicChanged(val ketogenic: Boolean) : ProductDetailEditEvent()
    data class OnProductLowFodmapChanged(val lowFodmap: Boolean) : ProductDetailEditEvent()
    data class OnProductOccasionsChanged(val occasions: List<String>) : ProductDetailEditEvent()
    data class OnProductSustainableChanged(val sustainable: Boolean) : ProductDetailEditEvent()
    data class OnProductVeganChanged(val vegan: Boolean) : ProductDetailEditEvent()
    data class OnProductVegetarianChanged(val vegetarian: Boolean) : ProductDetailEditEvent()
    data class OnProductVeryHealthyChanged(val veryHealthy: Boolean) : ProductDetailEditEvent()
    data class OnProductVeryPopularChanged(val veryPopular: Boolean) : ProductDetailEditEvent()
    data class OnProductWeightWatcherSmartPointsChanged(val weightWatcherSmartPoints: Int) : ProductDetailEditEvent()
    data class OnProductDishTypesChanged(val dishTypes: List<String>) : ProductDetailEditEvent()
    data class OnProductSummaryChanged(val summary: String) : ProductDetailEditEvent()
    class OnClickUndoProductDetail  : ProductDetailEditEvent()

}
